#! /bin/sh /usr/share/dpatch/dpatch-run
## 02_fix_header.dpatch by  <ikegam@james.mixallow.net>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: hh

@DPATCH@

15,16c15,16
< #include <libdwarf/libdwarf.h>
< #include <libdwarf/dwarf.h>
---
> #include <libdwarf.h>
> #include <dwarf.h>
