Document: ftrace
Title: Debian ftrace Manual
Author: <insert document author here>
Abstract: This manual describes what ftrace is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ftrace/ftrace.sgml.gz

Format: postscript
Files: /usr/share/doc/ftrace/ftrace.ps.gz

Format: text
Files: /usr/share/doc/ftrace/ftrace.text.gz

Format: HTML
Index: /usr/share/doc/ftrace/html/index.html
Files: /usr/share/doc/ftrace/html/*.html
